package com.sample
 
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import io.vertx.rxjava.core.eventbus.EventBus;
import io.vertx.core.buffer.Buffer;
import com.google.gson.Gson;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.Ask;

import java.lang.reflect.Type;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import com.google.gson.FieldNamingPolicy;
import io.vertx.core.json.JsonObject;
import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;

global java.lang.String REACT_APP_QWANDA_API_URL;
global java.lang.String REACT_APP_VERTX_URL;
global java.lang.String KEYCLOAKIP;

// global java.lang.String FACEBOOK_CLIENTID;
// global java.lang.String FACEBOOK_SECRET;
   


rule "FacebookRedirect"
    when
        $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "FACEBOOK" )
        bus: EventBus()
        $map : Map($value: this["token"] != null)
    then
        System.out.println("-------- Rule:- FACEBOOK REDIRECT RULE EXECUTED --------");
        
        String clientId = System.getenv("FACEBOOK_CLIENTID");
        String clientSecret =  System.getenv("FACEBOOK_SECRET");
        String redirectUrl =  "https://www.facebook.com/v2.8/dialog/oauth?response_type=code";
        System.out.println("This is CLIENT ID"+ clientId); 
        System.out.println("This is FB SECRET"+ clientSecret);
        System.out.println("This is redirect URL"+ redirectUrl);

        JsonObject data = new JsonObject ();
        data.put("clientId", clientId);
        data.put("clientSecret", clientSecret);
        data.put("redirectUrl", redirectUrl);

        System.out.println("*******************");
		System.out.println("Json Object: " +data.toString());	
		System.out.println("*******************");				

        JsonObject obj = new JsonObject();
        obj.put("msg_type", "DATA_MSG");
        obj.put("data_type", "FB_REDIRECT");
        obj.put("items", data);   
		
		System.out.println("*******************");
		System.out.println("Client ID and Secret: " +obj.toString());	
		System.out.println("*******************");						
		bus.publish("cmds", obj);      
end

